Update fortify-sast.yml

diff --git a/.github/workflows/fortify-sast.yml b/.github/workflows/fortify-sast.yml
--- a/.github/workflows/fortify-sast.yml
+++ b/.github/workflows/fortify-sast.yml
@@ -174,9 +174,9 @@ jobs:
                     fi
 
                     echo "Iniciando git blame e set tag author"
-                    # =========================================================================
-                    # Verifica se a tag Author existe
-                    # =========================================================================
+                    echo "========================================================================="
+                    echo "Verifica se a tag Author existe"
+                    echo "========================================================================="
                     echo "Verificando custom tags no Fortify..."
 
                     response=$(curl -s -w "%{http_code}" -H "Authorization: FortifyToken $fortify_unified_login_token" \
@@ -195,10 +195,9 @@ jobs:
                     fi
                     echo "Tag 'Author' encontrada! GUID: $guid"
 
-                    # ==============================================================================
-                    # Verifica se a tag Author já está aplicada ao projeto
-                    # ==============================================================================
-                    echo "Verificando se a tag Author está aplicada ao projeto..."
+                    echo "=============================================================================="
+                    echo "Verifica se a tag Author já está aplicada ao projeto..."
+                    echo "=============================================================================="
 
                     response=$(curl -s -w "%{http_code}" -H "Authorization: FortifyToken $fortify_unified_login_token" \
                     "$fortify_ssc_api_url/projectVersions/$fortify_project_id/customTags?start=0&limit=100")
@@ -224,9 +223,9 @@ jobs:
                         echo "Tag Author aplicada com sucesso!"
                     fi
 
-                    # ==============================================================================
-                    # Baixa issues do Fortify
-                    # ==============================================================================
+                    echo "=============================================================================="
+                    echo "Baixa issues do Fortify"
+                    echo "=============================================================================="
                     responseIssues=$(curl -s -w "%{http_code}" -g \
                         -X GET "$fortify_ssc_api_url/projectVersions/$fortify_project_version_id/issues?orderby=id" \
                         -H "Accept: application/json" -H "Content-Type: application/json" \
@@ -249,9 +248,16 @@ jobs:
                     echo "Arquivo salvo em: $VULN_FILE"
                     echo "Total de issues encontradas: $issue_count"
                     
-                    # ==============================================================================
-                    # Processa cada vulnerabilidade crítica/alta e aplica tag Author
-                    # ==============================================================================
+                    echo "=============================================================================="
+                    echo "Processa cada vulnerabilidade crítica/alta e aplica tag Author"
+                    echo "=============================================================================="
+
+                    # Verifica se o diretório é um repositório Git
+                    if ! git rev-parse --is-inside-work-tree &>/dev/null; then
+                        echo "Erro: este diretório não é um repositório Git. Abortando."
+                        exit 1
+                    fi
+
                     mapfile -t issues_array < <(jq -c '.data[] | select((.enginePriority=="Critical" or .enginePriority=="High") and (.issueStatus=="Unreviewed" or .primaryTag=="Exploitable"))' "$VULN_FILE")
                     
                     for issue in "${issues_array[@]}"; do
